/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author barry
 */
public class BioHigherMS extends javax.swing.JFrame {

    /**
     * Creates new form BioHigherMS
     */
    public BioHigherMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Title = new javax.swing.JLabel();
        sectionA = new javax.swing.JLabel();
        SectionB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SubA = new javax.swing.JLabel();
        SubA1 = new javax.swing.JLabel();
        SubA2 = new javax.swing.JLabel();
        SubA3 = new javax.swing.JLabel();
        SubA4 = new javax.swing.JLabel();
        SubA5 = new javax.swing.JLabel();
        SubA6 = new javax.swing.JLabel();
        SubA7 = new javax.swing.JLabel();
        SubA8 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Title.setText("Marking Scheme");

        sectionA.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        sectionA.setText("Section A:");

        SectionB.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        SectionB.setText("Section B:");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel3.setText("SectionC");

        SubA.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA.setText("Total marks:");

        SubA1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA1.setText("Tips:");

        SubA2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA2.setText("Timing:");

        SubA3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA3.setText("Total Marks:");

        SubA4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA4.setText("Timing:");

        SubA5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA5.setText("Tips:");

        SubA6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA6.setText("Total Marks:");

        SubA7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA7.setText("Tips:");

        SubA8.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        SubA8.setText("Timing:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SectionB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubA2)
                            .addComponent(SubA1)
                            .addComponent(SubA)
                            .addComponent(sectionA)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubA3)
                            .addComponent(SubA4)
                            .addComponent(SubA5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubA6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(SubA8)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubA7)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title)
                .addGap(67, 67, 67)
                .addComponent(sectionA)
                .addGap(18, 18, 18)
                .addComponent(SubA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(SubA2)
                .addGap(41, 41, 41)
                .addComponent(SubA1)
                .addGap(28, 28, 28)
                .addComponent(SectionB)
                .addGap(18, 18, 18)
                .addComponent(SubA3)
                .addGap(51, 51, 51)
                .addComponent(SubA4)
                .addGap(59, 59, 59)
                .addComponent(SubA5)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(SubA6)
                .addGap(50, 50, 50)
                .addComponent(SubA8)
                .addGap(48, 48, 48)
                .addComponent(SubA7)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioHigherMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioHigherMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioHigherMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioHigherMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioHigherMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SectionB;
    private javax.swing.JLabel SubA;
    private javax.swing.JLabel SubA1;
    private javax.swing.JLabel SubA2;
    private javax.swing.JLabel SubA3;
    private javax.swing.JLabel SubA4;
    private javax.swing.JLabel SubA5;
    private javax.swing.JLabel SubA6;
    private javax.swing.JLabel SubA7;
    private javax.swing.JLabel SubA8;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel sectionA;
    // End of variables declaration//GEN-END:variables
}
